// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem - PUNCH

#pragma once

#include <frc2/command/SubsystemBase.h>
#include <frc/DigitalInput.h>
#include <frc/motorcontrol/PWMSparkMax.h>
#include <rev/CANSparkMax.h>

enum {
    phase_0_notRunning,
    phase_1_inSensor,
    phase_2_exitSensor,
    phase_3_foundSensor
};

/**
 * header file for the punch
 *
 * @author WAVE Robotics 2826
 */
class Punch: public frc2::SubsystemBase {

public:

    Punch();

    void Periodic() override;
    void SimulationPeriodic() override;

    void SetBackPuncherSpeed(double speed);
    void SetFrontPuncherSpeed(double speed);

    bool GetBackCamSensor();
    bool GetFrontCamSensor();
   
    void runBackPuncher(bool run);
    void runFrontPuncher(bool run);
    
    double GetBackPuncherCurrent();
    double GetFrontPuncherCurrent();

private:

    frc::DigitalInput *m_backCamSensor;
    frc::DigitalInput *m_frontCamSensor;
    rev::CANSparkMax *m_backPuncher;
    rev::CANSparkMax *m_frontPuncher;

};

