// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem - TRANSPORTER

#pragma once

#include <frc2/command/SubsystemBase.h>
#include <frc/motorcontrol/PWMSparkMax.h>
#include <rev/CANSparkMax.h>

/**
 * header file for the transporter
 *
 * @author WAVE Robotics 2826
 */
class Transport: public frc2::SubsystemBase {

public:
    Transport();

    void Periodic() override; // Should be called all of the time from the system scheduler
    void SimulationPeriodic() override;

    void SetTransporterBeltSpeed(double speed);
    void SetIndexerSpeed(double leftSpeed, double rightSpeed); 
    
    double GetTransporterBeltCurrent();
    double GetRightIndexerCurrent();
    double GetLeftIndexerCurrent();
    
private:

    rev::CANSparkMax *m_transporterBelt;
    rev::CANSparkMax *m_rightIndexer;
    rev::CANSparkMax *m_leftIndexer;

};

