// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer

#pragma once

#include <frc/smartdashboard/SendableChooser.h>
#include <frc2/command/Command.h>

#include "subsystems/Climb.h"
#include "subsystems/Drive.h"
#include "subsystems/Intake.h"
#include "subsystems/Punch.h"
#include "subsystems/Transport.h"
#include "subsystems/Vision.h"

// need to include auto routines
#include "commands/AutonomousCommand.h"
#include "commands/Command1.h"
#include "commands/SequentialCommandGroup1.h"
#include "commands/SequentialPunch.h"
#include "commands/BackPunchCommand.h"
#include "commands/FrontPunchCommand.h"
#include "commands/DriveHeadingDistanceCommand.h"
#include "commands/SetpointCommand1.h"
#include "commands/WaitCommand1.h"
#include "commands/PunchAndExitTarmac.h"
#include "commands/DriveForwardTimed.h"
#include "commands/DeployIntakeCommand.h"
#include "commands/TransportCommand.h"
#include "commands/TwoBallAutoTimed.h"
#include "commands/ThreeBallAutoTimed.h"
#include "commands/ThreeBallAutoDistance.h"
#include "commands/TaxiTwoBallAuto.h"

#include <frc/XboxController.h>

class RobotContainer {

public:

    // The robot's commands
    // we aren't supposed to declare commands here???  
    // documentation says we should, but it breaks everything  
    // frc2::Command* PunchAndExitTarmac(); 
    // frc2::Command* BackPunchCommand();
    // frc2::Command* FrontPunchCommand(); 
    // frc2::Command* SequentialPunch();
    static RobotContainer* GetInstance();
    frc2::Command* GetAutonomousCommand();

    // The robot's subsystems
    Intake m_intake;
    Climb m_climb;
    Drive m_drive;
    Punch m_punch;
    Transport m_transport;
    Vision m_vision;
    
    // controllers
    frc::XboxController* getOperatorJS();
    frc::XboxController* getDriverJS();

private:

    RobotContainer();

    // controllers assigned ports
    frc::XboxController m_driverJS{0};
    frc::XboxController m_operatorJS{1};   

    // the chooser for the autonomous routines
    frc::SendableChooser<frc2::Command*> m_chooser;

    AutonomousCommand m_autonomousCommand;
    static RobotContainer* m_robotContainer;

    void ConfigureButtonBindings();
};

// This function is to call the GetInstance() from the .cpp file
// and return that singleton pointer
RobotContainer* GetContainer();