// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: WaitCommand - DRIVE COMMAND

#pragma once

#include <units/time.h>
#include "frc2/command/WaitCommand.h"
#include <frc2/command/CommandHelper.h>
#include <frc2/command/CommandBase.h>
#include <subsystems/Drive.h>

/**
 * header file for drive command
 *
 * @author WAVE Robotics 2826
 */
class DriveTurnCommand: public frc2::CommandHelper<frc2::CommandBase, DriveTurnCommand>{

public:

    DriveTurnCommand(double rotateInput, float turnAngle, Drive* drive);

    void Initialize() override;
    void Execute() override;
    bool IsFinished() override;
    void End(bool interrupted) override;
    bool RunsWhenDisabled() const override;

private:

    Drive* m_drive;
    units::second_t m_timeout;
    double m_rotateInput;
    float m_turnAngle;
    bool m_isTargetAngle;
    
};

