// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: WaitCommand - TRANSPORT COMMAND

#pragma once

#include <units/time.h>
#include "frc2/command/WaitCommand.h"
#include <frc2/command/CommandHelper.h>
#include <frc2/command/CommandBase.h>
#include <subsystems/Intake.h>
#include <subsystems/Transport.h>

/**
 * header file for transport command
 *
 * @author WAVE Robotics 2826
 */
class TransportCommand: public frc2::CommandHelper<frc2::CommandBase, TransportCommand> {

public:

    TransportCommand(Intake* intake, Transport* transport);

    void Initialize() override;
    void Execute() override;
    void End(bool interrupted) override;
    bool RunsWhenDisabled() const override;

private:

    Intake* m_intake;
    Transport* m_transport;
};