// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: WaitCommand.

#pragma once

#include <units/time.h>
#include "frc2/command/WaitCommand.h"
#include <frc2/command/CommandHelper.h>
#include <frc2/command/CommandBase.h>

/**
 * header file for the wait command
 * 
 * @author WAVE Robotics 2826
 */
class WaitCommand1: public frc2::WaitCommand {

public:

    explicit WaitCommand1(units::second_t timeout);
    // WaitCommand1(){};

    void Initialize() override;
    void Execute() override;
    void End(bool interrupted) override;
    bool RunsWhenDisabled() const override;

private:
    units::second_t m_timeout;
};

