// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: WaitCommand - DRIVE COMMAND

#include "commands/DriveHeadingCommand.h"
#include "commands/WaitCommand1.h"
#include "iostream"

/**
 * source code for drive command
 * 
 * @author WAVE Robotics 2826
 */
DriveHeadingCommand::DriveHeadingCommand(double moveInput, units::second_t timeout, Drive* drive) : WaitCommand(timeout),
    m_moveInput(moveInput), m_timeout(timeout), m_drive(drive)
{
    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(Robot::chassis.get());
    SetName("DriveHeadingCommand");
}

// Called just before this Command runs the first time
void DriveHeadingCommand::Initialize() {
    WaitCommand::Initialize();
}

// Called repeatedly when this Command is scheduled to run
void DriveHeadingCommand::Execute() {
    float angle_correction = -(m_drive->GetAngle() * 0.05f );
    // std::cout << "Angle" << m_drive->GetAngle() << std::endl;
    // std::cout << "Angle Correction" << angle_correction << std::endl;
    m_drive->arcadeDrive(m_moveInput, angle_correction);
}

// Called once after isFinished returns true
void DriveHeadingCommand::End(bool interrupted) {
    WaitCommand::End(interrupted);
    m_drive->arcadeDrive(0.0,0.0);
}

bool DriveHeadingCommand::RunsWhenDisabled() const {
    return false;
}