// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: WaitCommand - DRIVE COMMAND

#include "commands/DriveHeadingDistanceCommand.h"
#include "commands/WaitCommand1.h"
#include "iostream"

/**
 * source code for drive command
 * 
 * @author WAVE Robotics 2826
 */
DriveHeadingDistanceCommand::DriveHeadingDistanceCommand(double moveInput, double distance, Drive* drive):
    m_moveInput(moveInput), m_distance(distance), m_drive(drive)
{
    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(Robot::chassis.get());
    SetName("DriveHeadingDistanceCommand");
}

// Called just before this Command runs the first time
void DriveHeadingDistanceCommand::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void DriveHeadingDistanceCommand::Execute() {
    float angle_correction = -(m_drive->GetAngle() * 0.05f );
    m_drive->arcadeDrive(-m_moveInput, angle_correction);
}

bool DriveHeadingDistanceCommand::IsFinished() {
    if (m_drive->GetDriveEncoderPosition() < m_distance)
    {
        return false;
    }
    else
    {
        return true;
    }

}

// Called once after isFinished returns true
void DriveHeadingDistanceCommand::End(bool interrupted) {
    // reset drive encoder
    m_drive->ResetDrivePosition(m_drive->GetDriveEncoderPosition());
    m_drive->arcadeDrive(0.0,0.0);
}

bool DriveHeadingDistanceCommand::RunsWhenDisabled() const {
    return false;
}