// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup - HANGAR SIDE TWO BALL AUTO COMMAND

#include "commands/HangarSideTwoBallAuto.h"
#include "frc2/command/ParallelCommandGroup.h"
#include "commands/FrontPunchCommand.h"
#include "commands/SequentialPunch.h"
#include "commands/TransportCommand.h"
#include "commands/DeployIntakeCommand.h"
#include "commands/WaitCommand1.h"
#include <subsystems/Drive.h>
#include <subsystems/Intake.h>
#include <subsystems/Transport.h>
#include <subsystems/Punch.h>
#include "commands/DriveHeadingCommand.h"

/**
 * code for HANGER SIDE two ball auto using timings
 * fairly reliable despite using timings
 * INITIAL FRAMEOUT - NEEDS TUNING!
 * 
 * @author WAVE Robotics 2826
 */
HangarSideTwoBallAuto::HangarSideTwoBallAuto(Punch* punch, Drive* drive, Intake* intake, Transport* transport) {

    SetName("HangarSideTwoBallAuto");
    
    AddCommands(

                   
        frc2::ParallelCommandGroup
        (
            TransportCommand(intake, transport),
            DeployIntakeCommand(units::second_t(2), intake), 
            // score ball 1                   
            FrontPunchCommand(punch),         

            frc2::SequentialCommandGroup
            ( 
                WaitCommand1(units::second_t(1.5)),
                // forward ball 2 + taxi
                DriveHeadingCommand(-0.75, units::time::second_t(0.75), drive),
                DriveHeadingCommand(-0.15, units::time::second_t(0.2), drive),
                WaitCommand1(units::time::second_t(1.5)),
                // backwards to hub
                DriveHeadingCommand(0.75, units::time::second_t(0.75), drive),
                DriveHeadingCommand(0.15, units::time::second_t(0.2), drive),
                WaitCommand1(units::time::second_t(1.5)),
                // score ball 2
                FrontPunchCommand(punch)      
            )          
        )
    );
}

bool HangarSideTwoBallAuto::RunsWhenDisabled() const {
    return false;
}