// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup - SEQUENTIAL PUNCH

#include "commands/SequentialPunch.h"
#include "frc2/command/ParallelCommandGroup.h"
#include "commands/FrontPunchCommand.h"
#include "commands/BackPunchCommand.h"
#include "commands/WaitCommand1.h"
#include "iostream"

/**
 * code for sequential punch
 * 
 * @author WAVE Robotics 2826
 */
SequentialPunch::SequentialPunch(Punch* punch) : m_punch(punch) {

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("SequentialPunch");

    AddCommands(
        frc2::ParallelCommandGroup
            (
                BackPunchCommand(m_punch),
                frc2::SequentialCommandGroup
                (
                    WaitCommand1(units::second_t(0.425)),
                    FrontPunchCommand(m_punch)
                )
            )
    );    
}

bool SequentialPunch::RunsWhenDisabled() const {
    return false;
}