// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: WaitCommand - TRANSPORT COMMAND

#include "commands/TransportCommand.h"
#include "iostream"

/**
 * source code for transport command
 * 
 * @author WAVE Robotics 2826
 */
TransportCommand::TransportCommand(Intake* intake, Transport* transport) :
    m_intake(intake), m_transport(transport)
{
    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(Robot::chassis.get());
    SetName("TransportCommand");
}

// Called just before this Command runs the first time
void TransportCommand::Initialize() {
    
}

// Called repeatedly when this Command is scheduled to run
void TransportCommand::Execute() {
    m_intake->SetIntakeRoller(1.0);
    m_transport->SetIndexerSpeed(1.0, 1.0);
    m_transport->SetTransporterBeltSpeed(-1.0);
}

// Called once after isFinished returns true
void TransportCommand::End(bool interrupted) {
    m_intake->SetIntakeRoller(0.0);
    m_transport->SetIndexerSpeed(0.0, 0.0);
    m_transport->SetTransporterBeltSpeed(0.0);
}

bool TransportCommand::RunsWhenDisabled() const {
    return false;
}