// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: WaitCommand.


#include "commands/WaitCommand1.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

#include "commands/WaitCommand1.h"

WaitCommand1::WaitCommand1(units::second_t timeout) : WaitCommand(timeout),
    m_timeout(timeout)

{

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(Robot::chassis.get());
    SetName("WaitCommand1");

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

}

// Called just before this Command runs the first time
void WaitCommand1::Initialize() {
    WaitCommand::Initialize();
    // m_timer.Reset();
    // m_timer.Start();
}

// Called repeatedly when this Command is scheduled to run
void WaitCommand1::Execute() {

}

// Called once after isFinished returns true
void WaitCommand1::End(bool interrupted) {
    WaitCommand::End(interrupted);
    // m_timer.Stop();
}

bool WaitCommand1::RunsWhenDisabled() const {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}